### PR TITLE
DB app integration

### PR DESCRIPTION
**Pull request by alexaib2002**
This branch implements complete integration with the DB:

- UI insertion forms will adapt to their counterpart inside the BD by displaying all properties of the table
- UI deletion forms will adapt to their counterpart inside the DB by displaying the key about to be deleted, plus other optional fields (Customer ID & name...)
- UI modifications will be made from the main table located in the overview page.
- Tables will be displayed as tabs in the overview page. Users will be able to access their table view by clicking them.
 
Any other integration that may be needed MUST be discussed before this branch stops being a draft. Once I close this draft, no more changes will be allowed.

### CODE REVIEW

**Comment by alexaib2002** [comment]
Will close issues #6 and #7

**Review by Kaiscer — APPROVED** [review]
I agree with this

**Comment by alexaib2002** [comment]
The last commit 783e001 implements column creation based of the currently selected table, and populates said table with its rows from the DB. Thanks to the DataGrid component of MaterialUI, users can order and modify data easily without requiring any change to the actual codebase.

Only things left to do would be implementing registry additions, sending update requests to the backend every time a row is modified (may require adding a confirmation dialog) and implementing deletion.

**Review by deveshaha — APPROVED** [review]

**Comment by alexaib2002** [comment]
Branch was marked as a draft for a reason, it wasn't ready to be merged. Merge has been undone by force pushing an older version of main. All other related PRs will be remade the same way.

**Pull request merged**
